src/BulletPlugin/BulletCollisionDetector.cpp
src/BulletPlugin/CMakeLists.txt
src/BulletPlugin/python/PyBulletPlugin.cpp

Hello,
As the Bullet Plugin was broken, I took the liberty of fixing it (Since November according to  issue #19 ).
I had to remove the old Python code (createInstance) and modify the signature of some functions to match the bullet provided by Ubuntu 14.04. I also had to remove the NO_MODULE option in the CMakeLists which completely broke the build.
In addition, I had to turn off the double precision setting, but I suspect that this is because the package shipped by Ubuntu has it turned off, and thus did not include it in the commits.
All the best,
Hervé

Make bullet plugin work again

---

src/ODEPlugin/python/CMakeLists.txt

ENABLE_PYTHONとGAZEBO_ODEを両方有効にした場合にコンパイルエラーが出るので修正しました。

add gazebo ode version of python module

---

src/BodyPlugin/KinematicFaultChecker.cpp

Due to another bug, choreonoid seems like it does not import the Hrpsys waist files (*.pos, *.hip). Due to this, the pseq queue is empty when doing collision checks which results in crashes described in #38 .
As both at(size_t index) and operator[] have no safety checks, attempting to access an element of an empty queue results in a SIGFPE (Because we are basically attempting to do 0 % 0 when computing the position of the element).
In this pull request, I simply added guards in the problematic section of KinematicFaultChecker, but it would maybe be a better idea to throw the appropriate exception when doing an out-of-bounds access.
Cheers,
Hervé

Do not try to access pseq if it's empty in KinematicFaultChecker

---

src/Body/BodyMotionUtil.cpp
src/Util/MultiSE3Seq.cpp
src/Util/MultiSE3Seq.h

This pull request implements the loading of .hip files (Raw RPY notation). This is related to #38 in the sense that .hip files were not correctly loaded and triggered incorrect behaviour when no .waist files were present.
Before merging, we should decide on a correct behaviour when both .hip and .waist files are present. I think the waist file, containing more information should override the .hip file but I am not sure about it.
Another point that I would like to enhance is that now, by default, I set the translation to (0,0,0) when loading a .hip file. I think it would be better to keep the actual position, but AFAIK, this is not really possible in the current API.
Cheers,
Hervé

Correctly implement loading hip files

---

src/OpenRTMPlugin/VirtualRobotPortHandler.cpp

opencvのドキュメント(http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#projectpoints)
で
> If the vector is NULL/empty, the zero distortion coefficients are assumed
と言われているように、distortionのパラメータがemptyだとzeroの配列と解釈されると説明されています。
これはemptyでも良い、とも取れますが、シミュレータなので明示的に[0, 0, 0, 0, 0]と入れて上げてもいいかもしれないです。
関連して、
https://github.com/ros-perception/vision_opencv/pull/82
のような変更を加えました。
また、　https://github.com/start-jsk/rtmros_common/issues/859#issuecomment-156593708
のような報告もありました。

change D parameter as [0, 0, 0, 0, 0]

---

src/Util/VRMLWriter.h

以前、変更したVRMLWriterがinlineを使っていなかったため、複数個所でincludeしてリンクするとエラーになってしまったので修正しました。

use inline statement to prevent link error

---

src/PythonPlugin/PythonConsoleView.cpp

#22 であったようにchoreonoidのpythonインタプリタでipythonの様な高機能なインタプリタを使用したいということで，tab補完を実装してみました．
入力途中にtabを押すとカーソルの直前の単語を補完します
ただ，まだ完全なipythonの補完を再現出来ているわけだはなく
- importしたモジュールに対しては補完できるが，importする際には補完されない
- builtinメソッド等は補完されない
といった状態です
大まかには以下のような流れで実装しています．
1. カーソルより左の文字列をスペース,カンマ等で区切る
2. 1.で区切った最後の要素をドットで区切る
3. 2.で区切った要素をモジュール名としてdir(モジュール名)としてモジュールのメンバを取得する
4. 3で取得したメンバから"__"を含むものを削除する
5. 入力状態に合わせて適宜補完する

Add tab completion in python interpleter #22

---

src/PythonPlugin/PythonConsoleView.cpp

pythonインタプリタでいくつかのキーバインドを追加いたしまいした
- ctrl+p, ctrl+nで上矢印，下矢印に対応するコマンドヒストリの参照
- ctrl+f, ctrl+b, ctrl+a, ctrl+e でカーソルを左右，行頭行末へ移動
- ctrl+hでbackspace
ctrl+aはPR前はインタプリタ内の文字を全選択するようになっていましたが，一般的なpythonインタプリタでの挙動に合わせた方が良いかと思い，行頭への移動にoverwriteしました

Pythonインタプリタにキーバインドを追加

---

src/Body/VRMLBodyLoader.cpp

fkanehiro/choreonoid-editor#11 の要望に対応するためにVRMLのセグメント名をSgNodeのnameプロパティに格納するようにしました。
より適当な格納場所がありそうでしたらコメントください。

store vrml segment name to sgnode name

---

CMakeLists.txt
sample/GRobotPlugin/CMakeLists.txt
sample/HelloWorldPlugin/CMakeLists.txt
sample/Sample1Plugin/CMakeLists.txt
src/Base/ExtensionManager.cpp
src/Base/python/CMakeLists.txt
src/Base/python/PyQtCore.cpp
src/BulletPlugin/CMakeLists.txt
src/MediaPlugin/CMakeLists.txt
src/PythonPlugin/PythonConsoleView.cpp
src/RobotAccessPlugin/CMakeLists.txt

This fixes a bunch of compile-time errors when using Qt5.
There was also a possible error for Qt4 with QTimer's Python bindings: `QTimer::singleShot` was used instead of `QTimer::setSingleShot`. In Qt5, `singleShot` was also overloaded, so we're using the method that already existed in Qt4.
I also added an option to force the use of Qt5. The default behavior is still the same.

Fixes for Qt5

---

src/Util/ImageIO.cpp

This fixes the compilation for recent versions of libpng (fix #78). That problem seems fairly common (see [that other project](https://github.com/Galapix/galapix/commit/833a6b4ba0649269e3c309aa2f3761b329d0c84d) for instance).

Use proper PNG accessor functions instead of raw struct access

---

src/Base/GLSceneRenderer.cpp

While investigating `NaN`s in choreonoid, I found some unrelated issues in `GLSceneRenderer.cpp`, for instance this `0/0` in `setViewport`:
```txt
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff78b7144 in cnoid::GLSceneRendererImpl::setViewport (this=0x555555a7ae50, x=0x0, y=0x0, width=0x0, height=0x0) at choreonoid/src/Base/GLSceneRenderer.cpp:838
838         aspectRatio = (double)width / height;
```

Fix SIGFPE in aspect ratio computation

---

src/BodyPlugin/SensorVisualizerItem.cpp

力センサの可視化で力ベクトルの向きに回転がかかっていなかったのでかけるようにしました。(ref #84)

fixes a bug in sensor visualization

---

src/Util/CMakeLists.txt

SDKの利用に必要なヘッダが足りていなかったので加えました。

add missing header Exception.h

---

src/Body/python/PyBodyModule.cpp
src/Util/python/PyUtilModule.cpp

```
bodyMotion->frame(i) >> *body;
```
や
```
MultiValueSeq::Frame q = motion->jointPosSeq()->frame(i);
q[10] = 20.0;
```
のような操作をpythonから行いたかったのでBodyMotion周りでpythonインターフェースを追加してみました
ただし，MultiValueSeq::Frameクラスを取得するときにDeque2D＜double＞::Rowを作る必要があり，その辺りで少し不都合があるかもしれません．
c++での参照関係が
- MultiValueSeq
- MultiSeq＜double＞
- Deque2D ＜double, std::allocator＜double＞＞
- AbstractMultiSeq
となっているところを
[Util/python/PySeqTypes.cpp L.81](https://github.com/s-nakaoka/choreonoid/blob/master/src/Util/python/PySeqTypes.cpp#L81)で
pythonでは
- MultiValueSeq
- AbstractMultiSeq
となっていてDeque2Dを継承していないことになってる？ところにDeque2D＜double＞::Rowを実装してしまっています
(jointPosSeq()->frame(i)を呼ぶと最終的にDeque2D::Rowが返ってきてしまうので．．．)
motion->jointPosSeq()->frame(i)を呼ぶ分には問題ない様ですが，その他の場合に何か不都合がありますでしょうか?

BodyMotion周りのpythonインターフェースを追加

---

src/Body/python/PyBodyModule.cpp

pythonから逆運動学を行いたかったので，JointPathクラスをpythonに追加してみました
c++と同様に
```
jointpath = getCustomJointPath(robot, robot.link("LLEG_JOINT0"), robot.link("LLEG_JOINT5"))
pos = jointpath.endLink() + numpy.array([0,0,0.1])
jointpath.calcInverseKinematics(pos, jointpath.endLink().R)
```
のような感じでできるようになっていると思います
実装していて気づいたのですが，DoxygenでできるドキュメントにはcalcJacobianとcalcInverseKinematicsが「deprecated」となっているのですが，この2つのメソッドはよく使うと思うのですが，廃止予定なのでしょうか？
以上，宜しくお願い致します

逆運動学のpythonインターフェースを追加

---

src/Base/MainWindow.cpp

ステータスバーのチェック状態の復元にバグと思われる部分を見つけました。

fix a bug in the status bar check

---

src/Body/VRMLBodyWriter.cpp
src/Util/STLSceneLoader.cpp

前回お送りしたセンサノードのVRML出力フォーマットが一部間違っていたので修正しました。

fix vrml writing of sensor nodes

---

src/BodyPlugin/python/PySimulationClasses.cpp

シミュレータのロボットの位置を動かすためのpythonインタープリタを追加しました．
#103 のpython版にあたるものです
simulatorItem.setForcedPosition(<BodyItem>,<numpy.array>)
でロボットの位置が強制的に動いて，
simulatorItem.clearForcedPositions()
で強制保持が解除されると思います
もし，問題がなければマージしていただけると幸いです
宜しくお願い致します

BodyPlugin(python): add python interface for setForcedPosition and clearForcedPositions

---

src/Body/python/PyBodyModule.cpp

choreonoidでいつもお世話になっております。
東京大学情報システム工学研究室の小山と申します。
よろしくお願いいたします。
cnoid::Deviceのpythonインターフェイスを追加しました。
cnoid::Device::T_localの返り値の型がIsometry3で、こちらのpythonのconverterが提供されていないので、Positionにキャストしております。
https://github.com/s-nakaoka/choreonoid/commit/658d497471e6ff9e74862d2ea49fc3a31627333b#diff-642ec0c3fd6b1c94d32ff253dbea0908R120
Isometry3については、以下の部分で、
> // The followings should be removed later
となっていたので、Positionへのキャストとしたのですが、他の方法がよろしければ、ご教示ください。
https://github.com/s-nakaoka/choreonoid/blob/master/src/Util/EigenTypes.h#L75-L78
どうぞよろしくお願いいたします。

[src/Body/python/PyBodyModule.cpp] cnoid::Deviceのpythonインターフェイスを追加

---

.travis.yml
misc/docker/Dockerfile-ubuntu-xenial-clang
misc/docker/Dockerfile-ubuntu-xenial-gcc

C++テンプレートを多用するコードをgccでコンパイルすると遅いのでclangを使いたいなと思っているのですが、今のバージョンはclangだとコンパイルできないようです。
もし原因がわかったら解決策もPRで送りたいと思っていますが、まずはチェックするための環境を送ります。
travis-ciでフリーのアカウントを登録してレポジトリを有効化しておくと以下のような検証がコミット毎に出てきます。
https://travis-ci.org/yosuke/choreonoid

add Dockerfile and travis.yml to test compilation using clang

---

src/Base/CMakeLists.txt

外部プラグインにおいてinclude<cnoid/RectRegionMarker>とするとSceneWidgetEvent.hが見つからないとエラーが出ました．
SceneWidgetEvent.hがinstall時で入れるべきファイルリストから抜けているようでしたので
set( headers ...
でSceneWidgetEvent.hを追加しました．

add SceneWidgetEvent.h to headers

---

src/OpenRTMPlugin/deprecated/VirtualRobotPortHandler.cpp

I needed to access the robot's floating base acceleration (linear and angular) from the simulation. Seems like `ABS_ACCELERATION`was not defined, here is a working implementation.
Is this the proper way to achieve this?
I then use it as follow
```
out-port = waistAbsAcceleration:WAIST:ABS_ACCELERATION
```
And connect the correcponding port to my component.

Implement ABS_ACCELERATION

---

src/Body/BodyMotionUtil.cpp
src/Util/MultiSE3Seq.cpp
src/Util/MultiSE3Seq.h

hrpsysシーケンスファイルのwaistファイルの記述形式を修正しました．
修正した理由は
- hrpsys-baseの場合
http://fkanehiro.github.io/hrpsys-base/dd/d91/SequencePlayer.html
にもあるとおりルートリンクの位置姿勢の記述形式は「TimeStamp X Y Z Roll Pitch Yaw」
- GRXのhrpsysの場合
GRXのマニュアルを参照する限りだとhrpsys-baseと同じ記述形式
である一方
- choreonoidの場合
「TimeStamp X Y Z 姿勢行列要素(0,0) 姿勢行列要素(0,1) 姿勢行列要素(0,2) ..... 姿勢行列要素(2,2) 角速度」
のように姿勢をRPYではなく行列形式で記述するなっていたからです．
この様な実装になっているのは,hrpsys-baseとGRXのhrpsys以外のhrpsysシーケンスファイルを読み込めるシステムが存在するということでしょうか?
もしそうでしたら，今回のPRはRPYでのみ出力するようにしておりますので,共存できるように適当にマージしていただいて問題ありません．

hrpsysシーケンスファイルのwaistファイルの保存関数の修正

---

src/PoseSeqPlugin/Pose.cpp
src/PoseSeqPlugin/Pose.h
src/PoseSeqPlugin/PoseFilters.cpp
src/PoseSeqPlugin/PoseSeqItem.cpp
src/PoseSeqPlugin/PoseSeqViewBase.cpp

Pose::LinkInfoとPoseSeqファイルに接触リンクの接触点に関する情報を追加しました
コミットの概要は以下のようになっています
- LinkInfoのcontacttPoints_メンバ変数に接触点群が保持されます
- 各接触点は接触リンク固定座標系で表現されています
- PoseSeqファイルにはikLinkInfo内にcontactPointsというキーで点のリストが保存されます
- PoseSeqViewBase::setCurrentLinkStateToIkLink関数でcollidedというbool変数を削除し，代わりにcontactPoints(std::vector)のサイズでリンクが接触しているどうかを判断しています．その際に一つのリンクが複数の物体と干渉する際にbreak文は不都合なので削除しました

Poseへの接触点情報の追加

---

src/Body/Jacobian.cpp

角運動量ヤコビアンの計算が一部間違えていたので修正しました
確認として十分かどうかはわかりませんが，cnoid::Body::calcTotalMomentumの値を重心周りの角運動量に変換したものと値を比較して一致していることをいくつかの値で確認しました．
ここの実装は梶田先生の「分解運動量制御：運動量と角運動量に基づく ヒューマノイドロボットの全身運動生成」(10.7210/jrsj.22.772)の実装だと思いますが，
https://github.com/s-nakaoka/choreonoid/compare/master...kindsenior:PR-debug-angular-momentum-jacobian?expand=1#diff-fd82b28660151305f3fdfd1687a3aa32L218
の変更が式(1)のI~に対応していて，
https://github.com/s-nakaoka/choreonoid/compare/master...kindsenior:PR-debug-angular-momentum-jacobian?expand=1#diff-fd82b28660151305f3fdfd1687a3aa32L226
の変更が式(22)に対応すると思います

debug calcAngularMomentumJacobian

---

src/Body/pybind11/PyBodyModule.cpp

以下の3つの変更です
- Body* BodyLoader::load(const std::string& filename) をpythonから呼び出すためにBodyLoaderのコンストラクタのpythonインターフェイスを追加しました
- inline std::shared_ptr<JointPath> getCustomJointPath(Body* body, Link* baseLink, Link* endLink)がdeprecated なので static std::shared_ptr<JointPath> JointPath::getCustomPath(Body* body, Link* baseLink, Link* endLink) を呼び出すためのpythonインターフェイスを追加しました
- void calcJacobian(Eigen::MatrixXd& out_J)をpythonから呼び出すとout_Jの行列が参照渡しされていなかったので修正しました．
以前のコードだと以下のpythonの呼び出し方法ではヤコビアンが取得できず値が初期値のままでした．
```
from cnoid import Body, Base, BodyPlugin
body = Base.ItemTreeView.instance.selectedItem(BodyPlugin.BodyItem).body
jp = Body.getCustomJointPath(body, body.rootLink, body.link("joint name"))
J = numpy.ndarray((6,jp.numJoints))
jp.calcJacobian(J)
``` …

modify python interface for Body

---

cmake/ChoreonoidConfig.cmake.in

The documentation in `ChoreonoidConfig.cmake` says that to disable Qt setup we must set the `CHOREONOID_DISABLE_QT_SETUP` variable but the code actually uses `CHOREONOID_SKIP_QT_CONFIG`
This PR corrects the documentation

Fix comments in ChoreonoidConfig.cmake
